x-common: &common
  build:
    args:
      - DEV_UID=${DEV_UID:-1000}
      - DEV_GID=${DEV_GID:-1000}
    context: .
    dockerfile: docker/Dockerfile
  volumes:
    - type: bind
      source: .
      target: /app
    - type: bind
      source: ~/.cache/pnpm
      target: /home/node/.cache/pnpm
    - type: bind
      source: ~/.local/share/pnpm/store
      target: /home/node/.local/share/pnpm/store
  working_dir: /app

services:
  dev:
    <<: *common
    command:
      - pnpm
      - run
      - dev
      - "--host"
    expose:
      - 5173
    networks:
      - dev
    ports:
      - 5173:5173
    tty: true

  prod:
    <<: *common
    command:
      - pnpm
      - run
      - preview
      - "--host"
    expose:
      - 4173
    networks:
      - prod
    ports:
      - 4173:4173

networks:
  dev:
  prod:
