x-common: &common
  build:
    args:
      - DEV_UID=${DEV_UID:-1000}
      - DEV_GID=${DEV_GID:-1000}
    context: .
    dockerfile: docker/Dockerfile
  volumes:
    - type: bind
      source: .
      target: /home/bun/app
    - type: bind
      source: ~/.bun/install/cache
      target: /home/bun/.bun/install/cache
  working_dir: /home/bun/app

services:
  dev:
    <<: *common
    command:
      - bun
      - run
      - dev
    networks:
      - dev
    ports:
      - "3000:3000"

  prod:
    <<: *common
    command:
      - /bin/bash
      - -c
      - |
        bun run build
        bun run start
    networks:
      - prod
    ports:
      - "8000:3000"

networks:
  dev:
  prod:
