x-common: &common
  build:
    args:
      - DEV_UID=${DEV_UID:-1000}
      - DEV_GID=${DEV_GID:-1000}
    context: .
    dockerfile: docker/Dockerfile
  volumes:
    - type: bind
      source: .
      target: /home/bun/app
    - type: bind
      source: ~/.bun
      target: /home/bun/.bun
  working_dir: /home/bun/app

services:
  dev:
    <<: *common
    command:
      - bun
      - run
      - dev
      - "--host"
    expose:
      - 5173
    networks:
      - dev
    ports:
      - 5173:5173
    tty: true

  prod:
    <<: *common
    command:
      - bun
      - run
      - preview
      - "--host"
    expose:
      - 4173
    networks:
      - prod
    ports:
      - 4173:4173

networks:
  dev:
  prod:
