services:
  node:
    environment:
      YARN_CACHE_FOLDER: '/home/yarn-cache'
    # Netlify CLI needs Python, which is not present in "node:slim". So we use the full "node" image instead.
    image: node:18-slim
    ports:
      - '3000:3000'
    user: '${HOST_USER_IDS:-1000:1000}'
    volumes:
      - '.:/srv/app'
      - '${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/yarn-cache'
      - '${HOST_YARN_CONFIG_FOLDER:-~/.config/yarn}:/.yarn'
      - '${HOST_YARN_CONFIG_FILE:-~/.yarnrc}:/.yarnrc'
    working_dir: '/srv/app'
