version: '3'

silent: true

includes:
  setup:
    taskfile: ./taskfiles/setup.yaml
    aliases: [s]
  docker:
    taskfile: ./taskfiles/docker.yaml
    aliases: [d]
  dependencies:
    taskfile: ./taskfiles/dependencies.yaml
    aliases: [dep]
  run:
    taskfile: ./taskfiles/run.yaml
    aliases: [r]
  tests:
    taskfile: ./taskfiles/tests.yaml
    aliases: [t]

tasks:
  default:
    cmds:
      - task --list
