name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install project dependencies
        run: task dependencies:install
      - name: Check the code style
        run: task tests:static:prettier:check
      - name: Lint the stylesheets
        run: task tests:static:css:lint
      - name: Lint the application code
        run: task tests:static:ts:lint -- --format junit -o test_results/eslint.xml
      - name: Check the code typing
        run: task tests:static:types:check
      - name: Run unit tests
        run: task tests:unit:run -- --reporters=default --reporters=jest-junit
